const resList = [
  {
    info: {
      id: "871854",
      name: "Grillbox",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/17/5c1967f0-d347-435b-b525-e306cc46fa41_871854.jpg",
      locality: "Kanchan Business Centre",
      areaName: "Palghar",
      costForTwo: "₹299 for two",
      cuisines: ["Chinese", "Mughlai", "Indian", "Tandoor"],
      avgRating: 3.8,
      parentId: "511062",
      avgRatingString: "3.8",
      totalRatingsString: "3",
      sla: {
        deliveryTime: 30,
        lastMileTravel: 0.5,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "0.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 16:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3678c4ce-121b-427d-870e-3fb5bfb66490",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/grillbox-kanchan-business-centre-palghar-palghar-871854",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "838739",
      name: "Pranita s kitchen",
      cloudinaryImageId: "4d452913750e94da1a1fbddf7c1043ee",
      locality: "Palghar",
      areaName: "Palghar",
      costForTwo: "₹100 for two",
      cuisines: ["North Indian"],
      parentId: "497838",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 40,
        lastMileTravel: 0.5,
        serviceability: "SERVICEABLE",
        slaString: "35-40 mins",
        lastMileTravelString: "0.5 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 16:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3678c4ce-121b-427d-870e-3fb5bfb66490",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/pranita-s-kitchen-palghar-palghar-838739",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "865255",
      name: "FROSTING FUSION",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/2/6b9b82dc-e476-4ec6-bde8-9362b085ac89_865255.jpg",
      locality: "Palghar",
      areaName: "Palghar",
      costForTwo: "₹200 for two",
      cuisines: ["Bakery"],
      veg: true,
      parentId: "512932",
      avgRatingString: "NEW",
      sla: {
        deliveryTime: 28,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3678c4ce-121b-427d-870e-3fb5bfb66490",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/frosting-fusion-palghar-palghar-865255",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "706708",
      name: "Hotel Abhishek",
      cloudinaryImageId: "303676cd7a7a88916c382d93447cf1c9",
      locality: "Near Fish Market",
      areaName: "Palghar",
      costForTwo: "₹500 for two",
      cuisines: [
        "Chinese",
        "North Indian",
        "Kebabs",
        "Seafood",
        "Tandoor",
        "Beverages",
      ],
      avgRating: 3.8,
      parentId: "97722",
      avgRatingString: "3.8",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 30,
        lastMileTravel: 1.4,
        serviceability: "SERVICEABLE",
        slaString: "25-30 mins",
        lastMileTravelString: "1.4 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 23:15:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3678c4ce-121b-427d-870e-3fb5bfb66490",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/hotel-abhishek-near-fish-market-palghar-palghar-706708",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "723248",
      name: "Souffle Cake Shop",
      cloudinaryImageId: "fff68a70acf5a726257b6e7393f1ac93",
      locality: "panch balt",
      areaName: "Palghar",
      costForTwo: "₹400 for two",
      cuisines: ["Desserts", "Bakery"],
      avgRating: 4.2,
      veg: true,
      parentId: "230566",
      avgRatingString: "4.2",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 21,
        lastMileTravel: 0.9,
        serviceability: "SERVICEABLE",
        slaString: "20-25 mins",
        lastMileTravelString: "0.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 22:45:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "FREE ITEM",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3678c4ce-121b-427d-870e-3fb5bfb66490",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/souffle-cake-shop-panch-balt-palghar-palghar-723248",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "702016",
      name: "Cravings",
      cloudinaryImageId: "ff0ca9047e88527abb8aafdced3b7987",
      locality: "Palghar West",
      areaName: "Rajyog Elaenza,Char Rasta",
      costForTwo: "₹100 for two",
      cuisines: ["Chinese", "Pizzas", "Burgers", "Fast Food", "Snacks"],
      avgRating: 3.6,
      parentId: "2968",
      avgRatingString: "3.6",
      totalRatingsString: "10+",
      sla: {
        deliveryTime: 41,
        lastMileTravel: 0.8,
        serviceability: "SERVICEABLE",
        slaString: "40-45 mins",
        lastMileTravelString: "0.8 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 22:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      aggregatedDiscountInfoV3: {
        header: "10% OFF",
        subHeader: "ABOVE ₹350",
        discountTag: "FLAT DEAL",
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3678c4ce-121b-427d-870e-3fb5bfb66490",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/cravings-west-rajyog-elaenza-char-rasta-palghar-702016",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "707066",
      name: "Hotel Unnathi",
      cloudinaryImageId: "d889aea6e619903fe0b0ef3be15b8f50",
      locality: "Mahim Road",
      areaName: "Palghar",
      costForTwo: "₹400 for two",
      cuisines: [
        "Indian",
        "Punjabi",
        "Chinese",
        "Biryani",
        "Tandoor",
        "Thalis",
      ],
      avgRating: 3.9,
      parentId: "422810",
      avgRatingString: "3.9",
      totalRatingsString: "20+",
      sla: {
        deliveryTime: 32,
        lastMileTravel: 0.9,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "0.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 23:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3678c4ce-121b-427d-870e-3fb5bfb66490",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/hotel-unnathi-mahim-road-palghar-palghar-707066",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
  {
    info: {
      id: "798976",
      name: "Naadbramha Idli",
      cloudinaryImageId:
        "RX_THUMBNAIL/IMAGES/VENDOR/2024/4/22/5ca03869-a27d-46a6-8e8f-7d3e79fd499e_798976.JPG",
      locality: "Palghar",
      areaName: "Palghar",
      costForTwo: "₹100 for two",
      cuisines: ["South Indian", "Beverages"],
      avgRating: 4.4,
      parentId: "251339",
      avgRatingString: "4.4",
      totalRatingsString: "7",
      sla: {
        deliveryTime: 31,
        lastMileTravel: 0.9,
        serviceability: "SERVICEABLE",
        slaString: "30-35 mins",
        lastMileTravelString: "0.9 km",
        iconType: "ICON_TYPE_EMPTY",
      },
      availability: {
        nextCloseTime: "2024-05-12 20:00:00",
        opened: true,
      },
      badges: {},
      isOpen: true,
      aggregatedDiscountInfoV2: {},
      type: "F",
      badgesV2: {
        entityBadges: {
          imageBased: {},
          textBased: {},
          textExtendedBadges: {},
        },
      },
      orderabilityCommunication: {
        title: {},
        subTitle: {},
        message: {},
        customIcon: {},
      },
      differentiatedUi: {
        displayType: "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT",
        differentiatedUiMediaDetails: {
          mediaType: "ADS_MEDIA_ENUM_IMAGE",
          lottie: {},
          video: {},
        },
      },
      reviewsSummary: {},
      displayType: "RESTAURANT_DISPLAY_TYPE_DEFAULT",
      isNewlyOnboarded: true,
      restaurantOfferPresentationInfo: {},
    },
    analytics: {
      context: "seo-data-3678c4ce-121b-427d-870e-3fb5bfb66490",
    },
    cta: {
      link: "https://www.swiggy.com/restaurants/naadbramha-idli-palghar-palghar-798976",
      text: "RESTAURANT_MENU",
      type: "WEBLINK",
    },
    widgetId: "collectionV5RestaurantListWidget_SimRestoRelevance_food_seo",
  },
];
export default resList;
